import { RoleCode } from "@prisma/client";
import { Router } from "express";

import { attachOptionalAuth, requireAuth } from "../../middleware/auth.middleware.js";
import { requireRoles } from "../../middleware/roles.middleware.js";
import { validateBody, validateParams } from "../../middleware/validate.middleware.js";
import { asyncHandler } from "../../utils/async-handler.js";
import { commerceController } from "./commerce.controller.js";
import {
  addCartItemSchema,
  applyCheckoutCouponSchema,
  createCampaignSchema,
  createCouponSchema,
  createOrderSchema,
  createLoyaltyMembershipLevelSchema,
  createLoyaltyPointRuleSchema,
  createLoyaltyRewardSchema,
  createReferralRelationshipSchema,
  createReferralRuleSchema,
  createPricingRuleSchema,
  entityIdParamsSchema,
  manualLoyaltyAdjustmentSchema,
  mergeGuestCartSchema,
  previewProfitSchema,
  redeemLoyaltyRewardSchema,
  refundOrderSchema,
  reviewPaymentSchema,
  updateLoyaltyMembershipLevelSchema,
  updateLoyaltyPointRuleSchema,
  updateLoyaltyRewardSchema,
  updateProcurementTaskSchema,
  updatePreferredCurrencySchema,
  updateReferralRelationshipSchema,
  updateReferralRuleSchema,
  updateReferralUserCodeSchema,
  updateAdminOrderSchema,
  updateBusinessSettingsSchema,
  updateCampaignSchema,
  updateCouponSchema,
  updateSiteContentSettingsSchema,
  updateCartCountrySchema,
  updateCartItemSchema,
  updateOrderStatusSchema,
  updatePricingRuleSchema,
  updateProductPricingOverrideSchema,
  updateTrackingSchema,
  updatePaymentProviderConfigSchema,
  uploadPaymentReceiptSchema,
  upsertBankAccountSchema,
  upsertSourceSchema,
  upsertCustomerAddressSchema,
  upsertExchangeRateSchema,
  upsertShippingMethodSchema,
} from "./commerce.schemas.js";

export const commerceRouter = Router();

commerceRouter.use(attachOptionalAuth);

commerceRouter.get("/cart", asyncHandler(commerceController.getCart.bind(commerceController)));
commerceRouter.get("/site-content", asyncHandler(commerceController.getSiteContentSettings.bind(commerceController)));
commerceRouter.get("/campaigns/center-popup", asyncHandler(commerceController.getActiveCenterPopup.bind(commerceController)));
commerceRouter.post(
  "/cart/items",
  validateBody(addCartItemSchema),
  asyncHandler(commerceController.addCartItem.bind(commerceController)),
);
commerceRouter.patch(
  "/cart/items/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateCartItemSchema),
  asyncHandler(commerceController.updateCartItem.bind(commerceController)),
);
commerceRouter.delete(
  "/cart/items/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.removeCartItem.bind(commerceController)),
);
commerceRouter.delete("/cart/clear", asyncHandler(commerceController.clearCart.bind(commerceController)));
commerceRouter.patch(
  "/cart/country",
  validateBody(updateCartCountrySchema),
  asyncHandler(commerceController.updateCartCountry.bind(commerceController)),
);
commerceRouter.post(
  "/cart/merge",
  requireAuth,
  validateBody(mergeGuestCartSchema),
  asyncHandler(commerceController.mergeGuestCart.bind(commerceController)),
);
commerceRouter.get("/currencies/context", asyncHandler(commerceController.getCurrencyContext.bind(commerceController)));
commerceRouter.patch(
  "/currencies/preference",
  requireAuth,
  validateBody(updatePreferredCurrencySchema),
  asyncHandler(commerceController.updatePreferredCurrency.bind(commerceController)),
);

commerceRouter.post(
  "/checkout/preview-profit",
  requireAuth,
  requireRoles(RoleCode.SUPER_ADMIN, RoleCode.ADMIN),
  validateBody(previewProfitSchema),
  asyncHandler(commerceController.previewProfit.bind(commerceController)),
);

commerceRouter.get("/addresses", requireAuth, asyncHandler(commerceController.listAddresses.bind(commerceController)));
commerceRouter.post(
  "/addresses",
  requireAuth,
  validateBody(upsertCustomerAddressSchema),
  asyncHandler(commerceController.upsertAddress.bind(commerceController)),
);
commerceRouter.delete(
  "/addresses/:id",
  requireAuth,
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteAddress.bind(commerceController)),
);

commerceRouter.get(
  "/checkout",
  requireAuth,
  asyncHandler(commerceController.getCheckoutSummary.bind(commerceController)),
);
commerceRouter.post(
  "/checkout/orders",
  requireAuth,
  validateBody(createOrderSchema),
  asyncHandler(commerceController.createOrder.bind(commerceController)),
);
commerceRouter.post(
  "/checkout/promotion",
  requireAuth,
  validateBody(applyCheckoutCouponSchema),
  asyncHandler(commerceController.applyCheckoutCoupon.bind(commerceController)),
);
commerceRouter.delete(
  "/checkout/promotion",
  requireAuth,
  asyncHandler(commerceController.clearCheckoutCoupon.bind(commerceController)),
);

commerceRouter.get("/orders", requireAuth, asyncHandler(commerceController.listCustomerOrders.bind(commerceController)));
commerceRouter.get("/payments", requireAuth, asyncHandler(commerceController.listCustomerPayments.bind(commerceController)));
commerceRouter.get("/loyalty/me", requireAuth, asyncHandler(commerceController.getCustomerRewards.bind(commerceController)));
commerceRouter.get("/referrals/me", requireAuth, asyncHandler(commerceController.getCustomerReferrals.bind(commerceController)));
commerceRouter.post(
  "/loyalty/rewards/:id/redeem",
  requireAuth,
  validateParams(entityIdParamsSchema),
  validateBody(redeemLoyaltyRewardSchema),
  asyncHandler(commerceController.redeemReward.bind(commerceController)),
);
commerceRouter.post(
  "/payments/:id/receipt",
  requireAuth,
  validateParams(entityIdParamsSchema),
  validateBody(uploadPaymentReceiptSchema),
  asyncHandler(commerceController.uploadPaymentReceipt.bind(commerceController)),
);
commerceRouter.get(
  "/account/orders",
  requireAuth,
  asyncHandler(commerceController.listCustomerOrders.bind(commerceController)),
);

commerceRouter.use(
  [
    "/admin/pricing",
    "/admin/orders",
    "/admin/shipping",
    "/admin/settings/business",
    "/admin/site-content",
    "/admin/analytics/commerce",
    "/admin/sources",
    "/admin/procurement",
    "/admin/payments",
    "/admin/bank-accounts",
    "/admin/exchange-rates",
    "/admin/loyalty",
    "/admin/coupons",
    "/admin/campaigns",
    "/admin/referrals",
  ],
  requireAuth,
  requireRoles(RoleCode.SUPER_ADMIN, RoleCode.ADMIN),
);

commerceRouter.get(
  "/admin/pricing",
  asyncHandler(commerceController.getCommerceSettings.bind(commerceController)),
);
commerceRouter.get(
  "/admin/site-content",
  asyncHandler(commerceController.getSiteContentSettings.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/site-content",
  validateBody(updateSiteContentSettingsSchema),
  asyncHandler(commerceController.updateSiteContentSettings.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/pricing/business",
  validateBody(updateBusinessSettingsSchema),
  asyncHandler(commerceController.updateBusinessSettings.bind(commerceController)),
);
commerceRouter.post(
  "/admin/pricing/rules",
  validateBody(createPricingRuleSchema),
  asyncHandler(commerceController.createPricingRule.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/pricing/rules/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updatePricingRuleSchema),
  asyncHandler(commerceController.updatePricingRule.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/pricing/rules/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deletePricingRule.bind(commerceController)),
);
commerceRouter.get(
  "/admin/campaigns",
  asyncHandler(commerceController.getAdminCampaignOverview.bind(commerceController)),
);
commerceRouter.get(
  "/admin/campaigns/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.getAdminCampaign.bind(commerceController)),
);
commerceRouter.post(
  "/admin/campaigns",
  validateBody(createCampaignSchema),
  asyncHandler(commerceController.createCampaign.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/campaigns/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateCampaignSchema),
  asyncHandler(commerceController.updateCampaign.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/campaigns/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteCampaign.bind(commerceController)),
);
commerceRouter.get(
  "/admin/orders",
  asyncHandler(commerceController.listAdminOrders.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/orders/:id/status",
  validateParams(entityIdParamsSchema),
  validateBody(updateOrderStatusSchema),
  asyncHandler(commerceController.updateOrderStatus.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/orders/:id/tracking",
  validateParams(entityIdParamsSchema),
  validateBody(updateTrackingSchema),
  asyncHandler(commerceController.updateTrackingNumber.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/orders/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateAdminOrderSchema),
  asyncHandler(commerceController.updateAdminOrder.bind(commerceController)),
);
commerceRouter.post(
  "/admin/orders/:id/refund",
  validateParams(entityIdParamsSchema),
  validateBody(refundOrderSchema),
  asyncHandler(commerceController.refundOrder.bind(commerceController)),
);
commerceRouter.get(
  "/admin/procurement",
  asyncHandler(commerceController.getProcurementDashboard.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/procurement/tasks/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateProcurementTaskSchema),
  asyncHandler(commerceController.updateProcurementTask.bind(commerceController)),
);
commerceRouter.get(
  "/admin/payments",
  asyncHandler(commerceController.getAdminPayments.bind(commerceController)),
);
commerceRouter.get(
  "/admin/payments/review",
  asyncHandler(commerceController.getPaymentReviewQueue.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/payments/:id/review",
  validateParams(entityIdParamsSchema),
  validateBody(reviewPaymentSchema),
  asyncHandler(commerceController.reviewPayment.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/payments/:id/complete",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.completePayment.bind(commerceController)),
);
commerceRouter.get(
  "/admin/bank-accounts",
  asyncHandler(commerceController.listBankAccounts.bind(commerceController)),
);
commerceRouter.post(
  "/admin/bank-accounts",
  validateBody(upsertBankAccountSchema),
  asyncHandler(commerceController.upsertBankAccount.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/bank-accounts/:id",
  validateParams(entityIdParamsSchema),
  validateBody(upsertBankAccountSchema),
  asyncHandler(commerceController.upsertBankAccount.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/bank-accounts/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteBankAccount.bind(commerceController)),
);
commerceRouter.get(
  "/admin/exchange-rates",
  asyncHandler(commerceController.listExchangeRates.bind(commerceController)),
);
commerceRouter.get(
  "/admin/payments/providers",
  asyncHandler(commerceController.listPaymentProviderConfigs.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/payments/providers/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updatePaymentProviderConfigSchema),
  asyncHandler(commerceController.updatePaymentProviderConfig.bind(commerceController)),
);
commerceRouter.post(
  "/admin/exchange-rates",
  validateBody(upsertExchangeRateSchema),
  asyncHandler(commerceController.upsertExchangeRate.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/exchange-rates/:id",
  validateParams(entityIdParamsSchema),
  validateBody(upsertExchangeRateSchema),
  asyncHandler(commerceController.upsertExchangeRate.bind(commerceController)),
);
commerceRouter.post(
  "/admin/shipping/methods",
  validateBody(upsertShippingMethodSchema),
  asyncHandler(commerceController.upsertShippingMethod.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/shipping/methods/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteShippingMethod.bind(commerceController)),
);
commerceRouter.get(
  "/admin/settings/business",
  asyncHandler(commerceController.getCommerceSettings.bind(commerceController)),
);
commerceRouter.get(
  "/admin/analytics/commerce",
  asyncHandler(commerceController.getRevenueAnalytics.bind(commerceController)),
);
commerceRouter.get(
  "/admin/loyalty",
  asyncHandler(commerceController.getAdminLoyaltyOverview.bind(commerceController)),
);
commerceRouter.get(
  "/admin/coupons",
  asyncHandler(commerceController.getAdminCouponOverview.bind(commerceController)),
);
commerceRouter.get(
  "/admin/referrals",
  asyncHandler(commerceController.getAdminReferrals.bind(commerceController)),
);
commerceRouter.post(
  "/admin/referrals/rules",
  validateBody(createReferralRuleSchema),
  asyncHandler(commerceController.createReferralRule.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/referrals/rules/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateReferralRuleSchema),
  asyncHandler(commerceController.updateReferralRule.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/referrals/rules/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteReferralRule.bind(commerceController)),
);
commerceRouter.post(
  "/admin/referrals/relationships",
  validateBody(createReferralRelationshipSchema),
  asyncHandler(commerceController.createReferralRelationship.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/referrals/relationships/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateReferralRelationshipSchema),
  asyncHandler(commerceController.updateReferralRelationship.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/referrals/relationships/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteReferralRelationship.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/referrals/users/:id/code",
  validateParams(entityIdParamsSchema),
  validateBody(updateReferralUserCodeSchema),
  asyncHandler(commerceController.updateReferralUserCode.bind(commerceController)),
);
commerceRouter.post(
  "/admin/coupons",
  validateBody(createCouponSchema),
  asyncHandler(commerceController.createCoupon.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/coupons/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateCouponSchema),
  asyncHandler(commerceController.updateCoupon.bind(commerceController)),
);
commerceRouter.post(
  "/admin/coupons/:id/duplicate",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.duplicateCoupon.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/coupons/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteCoupon.bind(commerceController)),
);
commerceRouter.post(
  "/admin/loyalty/point-rules",
  validateBody(createLoyaltyPointRuleSchema),
  asyncHandler(commerceController.createLoyaltyPointRule.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/loyalty/point-rules/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateLoyaltyPointRuleSchema),
  asyncHandler(commerceController.updateLoyaltyPointRule.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/loyalty/point-rules/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteLoyaltyPointRule.bind(commerceController)),
);
commerceRouter.post(
  "/admin/loyalty/membership-levels",
  validateBody(createLoyaltyMembershipLevelSchema),
  asyncHandler(commerceController.createLoyaltyMembershipLevel.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/loyalty/membership-levels/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateLoyaltyMembershipLevelSchema),
  asyncHandler(commerceController.updateLoyaltyMembershipLevel.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/loyalty/membership-levels/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteLoyaltyMembershipLevel.bind(commerceController)),
);
commerceRouter.post(
  "/admin/loyalty/rewards",
  validateBody(createLoyaltyRewardSchema),
  asyncHandler(commerceController.createLoyaltyReward.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/loyalty/rewards/:id",
  validateParams(entityIdParamsSchema),
  validateBody(updateLoyaltyRewardSchema),
  asyncHandler(commerceController.updateLoyaltyReward.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/loyalty/rewards/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteLoyaltyReward.bind(commerceController)),
);
commerceRouter.post(
  "/admin/loyalty/manual-adjustments",
  validateBody(manualLoyaltyAdjustmentSchema),
  asyncHandler(commerceController.createLoyaltyManualAdjustment.bind(commerceController)),
);
commerceRouter.get(
  "/admin/sources",
  asyncHandler(commerceController.listSources.bind(commerceController)),
);
commerceRouter.post(
  "/admin/sources",
  validateBody(upsertSourceSchema),
  asyncHandler(commerceController.upsertSource.bind(commerceController)),
);
commerceRouter.delete(
  "/admin/sources/:id",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.deleteSource.bind(commerceController)),
);
commerceRouter.get(
  "/admin/products/:id/source-info",
  validateParams(entityIdParamsSchema),
  asyncHandler(commerceController.getProductCommerceDetail.bind(commerceController)),
);
commerceRouter.patch(
  "/admin/products/:id/pricing-override",
  validateParams(entityIdParamsSchema),
  validateBody(updateProductPricingOverrideSchema),
  asyncHandler(commerceController.updateProductPricingOverride.bind(commerceController)),
);
