import { z } from "zod";

const heroSlideSchema = z.object({
  id: z.string().trim().min(1).max(120),
  eyebrow: z.string().trim().min(1).max(120),
  titleTop: z.string().trim().min(1).max(160),
  titleAccent: z.string().trim().min(1).max(160),
  description: z.string().trim().min(1).max(500),
  primaryLabel: z.string().trim().min(1).max(80),
  primaryHref: z.string().trim().min(1).max(255),
  secondaryLabel: z.string().trim().min(1).max(80),
  secondaryHref: z.string().trim().min(1).max(255),
  imageUrl: z.string().trim().min(1).max(2048),
  overlayFrom: z.string().trim().min(1).max(64),
  overlayVia: z.string().trim().min(1).max(64),
  overlayTo: z.string().trim().min(1).max(64),
  cardEyebrow: z.string().trim().min(1).max(120),
  cardTitle: z.string().trim().min(1).max(180),
  cardDescription: z.string().trim().min(1).max(400),
});

const trustBadgeSchema = z.object({
  id: z.string().trim().min(1).max(120),
  icon: z.enum(["truck", "shield", "return", "support"]),
  title: z.string().trim().min(1).max(120),
  description: z.string().trim().min(1).max(180),
});

const heroStatSchema = z.object({
  id: z.string().trim().min(1).max(120),
  label: z.string().trim().min(1).max(120),
  value: z.number().nonnegative(),
  suffix: z.string().trim().max(20),
});

const footerLinkSchema = z.object({
  id: z.string().trim().min(1).max(120),
  label: z.string().trim().min(1).max(120),
  href: z.string().trim().min(1).max(255),
});

export const siteContentSettingsSchema = z.object({
  siteName: z.string().trim().min(1).max(120),
  siteTagline: z.string().trim().min(1).max(120),
  announcementBar: z.object({
    enabled: z.boolean(),
    leftText: z.string().trim().min(1).max(180),
    rightText: z.string().trim().min(1).max(180),
    signInLabel: z.string().trim().min(1).max(80),
    wishlistLabel: z.string().trim().min(1).max(80),
  }),
  header: z.object({
    logoTop: z.string().trim().min(1).max(80),
    logoBottom: z.string().trim().min(1).max(80),
    shopLabel: z.string().trim().min(1).max(80),
    searchPlaceholder: z.string().trim().min(1).max(180),
    accountLabel: z.string().trim().min(1).max(80),
    cartLabel: z.string().trim().min(1).max(80),
    wishlistLabel: z.string().trim().min(1).max(80),
  }),
  seo: z.object({
    defaultTitle: z.string().trim().min(1).max(160),
    titleSuffix: z.string().trim().max(120),
    description: z.string().trim().min(1).max(320),
    keywords: z.string().trim().max(500),
    ogImageUrl: z.string().trim().min(1).max(2048),
    canonicalBaseUrl: z.string().trim().max(2048),
    robots: z.string().trim().max(120),
  }),
  heroSlides: z.array(heroSlideSchema).min(1).max(8),
  heroStats: z.array(heroStatSchema).min(1).max(6),
  brandMarquee: z.array(z.string().trim().min(1).max(80)).min(1).max(20),
  homeSections: z.object({
    newArrivalsTitle: z.string().trim().min(1).max(120),
    newArrivalsCtaLabel: z.string().trim().min(1).max(80),
    newArrivalsCtaHref: z.string().trim().min(1).max(255),
    categoriesTitle: z.string().trim().min(1).max(120),
    promoTitle: z.string().trim().min(1).max(180),
    promoButtonLabel: z.string().trim().min(1).max(80),
    promoButtonHref: z.string().trim().min(1).max(255),
    bestSellersTitle: z.string().trim().min(1).max(120),
    bestSellersCtaLabel: z.string().trim().min(1).max(80),
    bestSellersCtaHref: z.string().trim().min(1).max(255),
    trustBadgesTitle: z.string().trim().min(1).max(120),
  }),
  trustBadges: z.array(trustBadgeSchema).min(1).max(8),
  footer: z.object({
    newsletterEyebrow: z.string().trim().min(1).max(120),
    newsletterTitle: z.string().trim().min(1).max(220),
    newsletterPlaceholder: z.string().trim().min(1).max(120),
    newsletterButtonLabel: z.string().trim().min(1).max(80),
    description: z.string().trim().min(1).max(320),
    shopTitle: z.string().trim().min(1).max(80),
    supportTitle: z.string().trim().min(1).max(80),
    aboutTitle: z.string().trim().min(1).max(80),
    copyright: z.string().trim().min(1).max(180),
    instagramUrl: z.string().trim().url(),
    twitterUrl: z.string().trim().url(),
    facebookUrl: z.string().trim().url(),
    shopLinks: z.array(footerLinkSchema).min(1).max(8),
    supportLinks: z.array(footerLinkSchema).min(1).max(8),
    aboutLinks: z.array(footerLinkSchema).min(1).max(8),
  }),
});

export type SiteContentSettings = z.infer<typeof siteContentSettingsSchema>;

export const DEFAULT_SITE_CONTENT_SETTINGS: SiteContentSettings = {
  siteName: "OutletHub",
  siteTagline: "Luxe Hub",
  announcementBar: {
    enabled: true,
    leftText: "Premium brands, outlet prices",
    rightText: "Free shipping on qualifying orders",
    signInLabel: "Sign in / Register",
    wishlistLabel: "Wishlist",
  },
  header: {
    logoTop: "OUTLET",
    logoBottom: "Luxe Hub",
    shopLabel: "Shop",
    searchPlaceholder: "Search for products, brands...",
    accountLabel: "My Account",
    cartLabel: "Cart",
    wishlistLabel: "Wishlist",
  },
  seo: {
    defaultTitle: "OutletHub | Luxury Outlet Fashion",
    titleSuffix: "OutletHub",
    description: "Shop premium fashion brands at outlet prices with a refined luxury storefront experience.",
    keywords: "outlet fashion,luxury brands,designer outlet,premium clothing,OutletHub",
    ogImageUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1400&q=80",
    canonicalBaseUrl: "",
    robots: "index,follow",
  },
  heroSlides: [
    {
      id: "slide-1",
      eyebrow: "Fall Essentials",
      titleTop: "Update Your Wardrobe.",
      titleAccent: "Shop the New Collection",
      description: "A polished storefront experience with premium fashion, refined layouts, and elevated visual storytelling.",
      primaryLabel: "Shop Men",
      primaryHref: "/shop?gender=men",
      secondaryLabel: "Shop Women",
      secondaryHref: "/shop?gender=women",
      imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1600&q=80",
      overlayFrom: "rgba(14,18,26,0.72)",
      overlayVia: "rgba(14,18,26,0.35)",
      overlayTo: "rgba(14,18,26,0.10)",
      cardEyebrow: "Season Spotlight",
      cardTitle: "A refined edit for modern wardrobes.",
      cardDescription: "Tailored silhouettes, premium textures, and elevated essentials for a boutique-style first impression.",
    },
    {
      id: "slide-2",
      eyebrow: "New Arrival Edit",
      titleTop: "Luxury Layers.",
      titleAccent: "Refined Daily Style",
      description: "Present your products with cleaner composition, softer body tones, and premium campaign-style hero content.",
      primaryLabel: "New Arrivals",
      primaryHref: "/shop?sort=newest",
      secondaryLabel: "Shop All",
      secondaryHref: "/shop",
      imageUrl: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=80",
      overlayFrom: "rgba(18,22,32,0.65)",
      overlayVia: "rgba(18,22,32,0.28)",
      overlayTo: "rgba(18,22,32,0.08)",
      cardEyebrow: "Storefront Styling",
      cardTitle: "Every hero slide is editable from admin.",
      cardDescription: "Update slide images, CTA labels, overlay mood, and all supporting text without touching code.",
    },
  ],
  heroStats: [
    { id: "stat-1", label: "Brands", value: 200, suffix: "+" },
    { id: "stat-2", label: "Products", value: 15000, suffix: "+" },
    { id: "stat-3", label: "Avg. Savings", value: 45, suffix: "%" },
  ],
  brandMarquee: [
    "NIKE",
    "ADIDAS",
    "TOMMY HILFIGER",
    "CALVIN KLEIN",
    "GUESS",
    "HUGO BOSS",
    "MICHAEL KORS",
    "COACH",
  ],
  homeSections: {
    newArrivalsTitle: "New Arrivals",
    newArrivalsCtaLabel: "View all",
    newArrivalsCtaHref: "/shop?sort=newest",
    categoriesTitle: "Shop By Category",
    promoTitle: "Mid-Season Edit | Refined Outlet Picks",
    promoButtonLabel: "Shop Sale",
    promoButtonHref: "/shop?is_trending=true",
    bestSellersTitle: "Best Sellers",
    bestSellersCtaLabel: "View all",
    bestSellersCtaHref: "/shop",
    trustBadgesTitle: "Trust Badges",
  },
  trustBadges: [
    { id: "badge-1", icon: "truck", title: "Free Shipping", description: "On qualifying orders" },
    { id: "badge-2", icon: "shield", title: "Secure Payment", description: "Protected checkout" },
    { id: "badge-3", icon: "return", title: "30-Day Returns", description: "Easy returns support" },
    { id: "badge-4", icon: "support", title: "24/7 Support", description: "We are here to help" },
  ],
  footer: {
    newsletterEyebrow: "Join The OutletHub Club",
    newsletterTitle: "New arrivals, private offers, and curated outlet drops.",
    newsletterPlaceholder: "Enter your email address",
    newsletterButtonLabel: "Subscribe",
    description: "Premium brands, curated outlet prices, and a refined shopping journey from discovery to delivery.",
    shopTitle: "SHOP",
    supportTitle: "CUSTOMER CARE",
    aboutTitle: "ABOUT",
    copyright: "© 2026 OutletHub. All rights reserved.",
    instagramUrl: "https://instagram.com",
    twitterUrl: "https://twitter.com",
    facebookUrl: "https://facebook.com",
    shopLinks: [
      { id: "shop-link-1", label: "Women", href: "/shop?gender=women" },
      { id: "shop-link-2", label: "Men", href: "/shop?gender=men" },
      { id: "shop-link-3", label: "Trending", href: "/shop?is_trending=true" },
      { id: "shop-link-4", label: "All Products", href: "/shop" },
    ],
    supportLinks: [
      { id: "support-link-1", label: "Contact Us", href: "/contact" },
      { id: "support-link-2", label: "Shipping Info", href: "/shipping" },
      { id: "support-link-3", label: "Returns & Exchanges", href: "/returns" },
      { id: "support-link-4", label: "FAQ", href: "/faq" },
    ],
    aboutLinks: [
      { id: "about-link-1", label: "About", href: "/about" },
      { id: "about-link-2", label: "Privacy Policy", href: "/privacy" },
      { id: "about-link-3", label: "Terms of Service", href: "/terms" },
      { id: "about-link-4", label: "My Account", href: "/dashboard" },
    ],
  },
};

export function resolveSiteContentSettings(input: unknown): SiteContentSettings {
  const parsed = siteContentSettingsSchema.safeParse(input);
  return parsed.success ? parsed.data : DEFAULT_SITE_CONTENT_SETTINGS;
}
